import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { listFirstClassModelCatalog } from "../src/pi/model-provider-catalog.js";

const destination = resolve(import.meta.dirname, "../src/pi/model-catalog.generated.ts");
const catalog = listFirstClassModelCatalog();
const source = `// Generated by npm run generate:pi-model-catalog. Do not edit by hand.\nimport type { ModelCatalogEntry } from "./model-provider-metadata.js";\n\nexport const firstClassModelCatalog = ${JSON.stringify(catalog, null, 2)} as const satisfies readonly ModelCatalogEntry[];\n`;

writeFileSync(destination, source, "utf8");
