// Generated by npm run generate:pi-model-catalog. Do not edit by hand.
import type { ModelCatalogEntry } from "./model-provider-metadata.js";

export const firstClassModelCatalog = [
  {
    provider: "google",
    id: "deep-research-max-preview-04-2026",
    label: "google/deep-research-max-preview-04-2026",
  },
  {
    provider: "google",
    id: "deep-research-preview-04-2026",
    label: "google/deep-research-preview-04-2026",
  },
  {
    provider: "google",
    id: "gemini-2.0-flash",
    label: "google/gemini-2.0-flash",
  },
  {
    provider: "google",
    id: "gemini-2.0-flash-lite",
    label: "google/gemini-2.0-flash-lite",
  },
  {
    provider: "google",
    id: "gemini-2.5-computer-use-preview-10-2025",
    label: "google/gemini-2.5-computer-use-preview-10-2025",
  },
  {
    provider: "google",
    id: "gemini-2.5-flash",
    label: "google/gemini-2.5-flash",
  },
  {
    provider: "google",
    id: "gemini-2.5-flash-lite",
    label: "google/gemini-2.5-flash-lite",
  },
  {
    provider: "google",
    id: "gemini-2.5-pro",
    label: "google/gemini-2.5-pro",
  },
  {
    provider: "google",
    id: "gemini-3-flash-preview",
    label: "google/gemini-3-flash-preview",
  },
  {
    provider: "google",
    id: "gemini-3-pro-preview",
    label: "google/gemini-3-pro-preview",
  },
  {
    provider: "google",
    id: "gemini-3.1-flash-lite",
    label: "google/gemini-3.1-flash-lite",
  },
  {
    provider: "google",
    id: "gemini-3.1-flash-lite-image",
    label: "google/gemini-3.1-flash-lite-image",
  },
  {
    provider: "google",
    id: "gemini-3.1-flash-lite-preview",
    label: "google/gemini-3.1-flash-lite-preview",
  },
  {
    provider: "google",
    id: "gemini-3.1-flash-live-preview",
    label: "google/gemini-3.1-flash-live-preview",
  },
  {
    provider: "google",
    id: "gemini-3.1-pro-preview",
    label: "google/gemini-3.1-pro-preview",
  },
  {
    provider: "google",
    id: "gemini-3.1-pro-preview-customtools",
    label: "google/gemini-3.1-pro-preview-customtools",
  },
  {
    provider: "google",
    id: "gemini-3.5-flash",
    label: "google/gemini-3.5-flash",
  },
  {
    provider: "google",
    id: "gemini-3.5-flash-lite",
    label: "google/gemini-3.5-flash-lite",
  },
  {
    provider: "google",
    id: "gemini-3.6-flash",
    label: "google/gemini-3.6-flash",
  },
  {
    provider: "google",
    id: "gemini-flash-latest",
    label: "google/gemini-flash-latest",
  },
  {
    provider: "google",
    id: "gemini-flash-lite-latest",
    label: "google/gemini-flash-lite-latest",
  },
  {
    provider: "google",
    id: "gemini-robotics-er-1.6-preview",
    label: "google/gemini-robotics-er-1.6-preview",
  },
  {
    provider: "google",
    id: "gemma-4-26b-a4b-it",
    label: "google/gemma-4-26b-a4b-it",
  },
  {
    provider: "google",
    id: "gemma-4-31b-it",
    label: "google/gemma-4-31b-it",
  },
  {
    provider: "openai",
    id: "gpt-4",
    label: "openai/gpt-4",
  },
  {
    provider: "openai",
    id: "gpt-4-turbo",
    label: "openai/gpt-4-turbo",
  },
  {
    provider: "openai",
    id: "gpt-4.1",
    label: "openai/gpt-4.1",
  },
  {
    provider: "openai",
    id: "gpt-4.1-mini",
    label: "openai/gpt-4.1-mini",
  },
  {
    provider: "openai",
    id: "gpt-4.1-nano",
    label: "openai/gpt-4.1-nano",
  },
  {
    provider: "openai",
    id: "gpt-4o",
    label: "openai/gpt-4o",
  },
  {
    provider: "openai",
    id: "gpt-4o-2024-05-13",
    label: "openai/gpt-4o-2024-05-13",
  },
  {
    provider: "openai",
    id: "gpt-4o-2024-08-06",
    label: "openai/gpt-4o-2024-08-06",
  },
  {
    provider: "openai",
    id: "gpt-4o-2024-11-20",
    label: "openai/gpt-4o-2024-11-20",
  },
  {
    provider: "openai",
    id: "gpt-4o-mini",
    label: "openai/gpt-4o-mini",
  },
  {
    provider: "openai",
    id: "gpt-5",
    label: "openai/gpt-5",
  },
  {
    provider: "openai",
    id: "gpt-5-chat-latest",
    label: "openai/gpt-5-chat-latest",
  },
  {
    provider: "openai",
    id: "gpt-5-mini",
    label: "openai/gpt-5-mini",
  },
  {
    provider: "openai",
    id: "gpt-5-nano",
    label: "openai/gpt-5-nano",
  },
  {
    provider: "openai",
    id: "gpt-5-pro",
    label: "openai/gpt-5-pro",
  },
  {
    provider: "openai",
    id: "gpt-5.1",
    label: "openai/gpt-5.1",
  },
  {
    provider: "openai",
    id: "gpt-5.2",
    label: "openai/gpt-5.2",
  },
  {
    provider: "openai",
    id: "gpt-5.2-chat-latest",
    label: "openai/gpt-5.2-chat-latest",
  },
  {
    provider: "openai",
    id: "gpt-5.2-pro",
    label: "openai/gpt-5.2-pro",
  },
  {
    provider: "openai",
    id: "gpt-5.3-chat-latest",
    label: "openai/gpt-5.3-chat-latest",
  },
  {
    provider: "openai",
    id: "gpt-5.3-codex",
    label: "openai/gpt-5.3-codex",
  },
  {
    provider: "openai",
    id: "gpt-5.3-codex-spark",
    label: "openai/gpt-5.3-codex-spark",
  },
  {
    provider: "openai",
    id: "gpt-5.4",
    label: "openai/gpt-5.4",
  },
  {
    provider: "openai",
    id: "gpt-5.4-mini",
    label: "openai/gpt-5.4-mini",
  },
  {
    provider: "openai",
    id: "gpt-5.4-nano",
    label: "openai/gpt-5.4-nano",
  },
  {
    provider: "openai",
    id: "gpt-5.4-pro",
    label: "openai/gpt-5.4-pro",
  },
  {
    provider: "openai",
    id: "gpt-5.5",
    label: "openai/gpt-5.5",
  },
  {
    provider: "openai",
    id: "gpt-5.5-pro",
    label: "openai/gpt-5.5-pro",
  },
  {
    provider: "openai",
    id: "gpt-5.6-luna",
    label: "openai/gpt-5.6-luna",
  },
  {
    provider: "openai",
    id: "gpt-5.6-sol",
    label: "openai/gpt-5.6-sol",
  },
  {
    provider: "openai",
    id: "gpt-5.6-terra",
    label: "openai/gpt-5.6-terra",
  },
  {
    provider: "openai",
    id: "gpt-realtime-2.1",
    label: "openai/gpt-realtime-2.1",
  },
  {
    provider: "openai",
    id: "o1",
    label: "openai/o1",
  },
  {
    provider: "openai",
    id: "o1-pro",
    label: "openai/o1-pro",
  },
  {
    provider: "openai",
    id: "o3",
    label: "openai/o3",
  },
  {
    provider: "openai",
    id: "o3-mini",
    label: "openai/o3-mini",
  },
  {
    provider: "openai",
    id: "o3-pro",
    label: "openai/o3-pro",
  },
  {
    provider: "openai",
    id: "o4-mini",
    label: "openai/o4-mini",
  },
  {
    provider: "anthropic",
    id: "claude-fable-5",
    label: "anthropic/claude-fable-5",
  },
  {
    provider: "anthropic",
    id: "claude-haiku-4-5",
    label: "anthropic/claude-haiku-4-5",
  },
  {
    provider: "anthropic",
    id: "claude-haiku-4-5-20251001",
    label: "anthropic/claude-haiku-4-5-20251001",
  },
  {
    provider: "anthropic",
    id: "claude-opus-4-1",
    label: "anthropic/claude-opus-4-1",
  },
  {
    provider: "anthropic",
    id: "claude-opus-4-1-20250805",
    label: "anthropic/claude-opus-4-1-20250805",
  },
  {
    provider: "anthropic",
    id: "claude-opus-4-5",
    label: "anthropic/claude-opus-4-5",
  },
  {
    provider: "anthropic",
    id: "claude-opus-4-5-20251101",
    label: "anthropic/claude-opus-4-5-20251101",
  },
  {
    provider: "anthropic",
    id: "claude-opus-4-6",
    label: "anthropic/claude-opus-4-6",
  },
  {
    provider: "anthropic",
    id: "claude-opus-4-7",
    label: "anthropic/claude-opus-4-7",
  },
  {
    provider: "anthropic",
    id: "claude-opus-4-8",
    label: "anthropic/claude-opus-4-8",
  },
  {
    provider: "anthropic",
    id: "claude-opus-5",
    label: "anthropic/claude-opus-5",
  },
  {
    provider: "anthropic",
    id: "claude-sonnet-4-5",
    label: "anthropic/claude-sonnet-4-5",
  },
  {
    provider: "anthropic",
    id: "claude-sonnet-4-5-20250929",
    label: "anthropic/claude-sonnet-4-5-20250929",
  },
  {
    provider: "anthropic",
    id: "claude-sonnet-4-6",
    label: "anthropic/claude-sonnet-4-6",
  },
  {
    provider: "anthropic",
    id: "claude-sonnet-5",
    label: "anthropic/claude-sonnet-5",
  },
] as const satisfies readonly ModelCatalogEntry[];
